### ISSUE TITLE
Use visual cues instead of toast notifications when typing to a textarea

### ISSUE THREAD

**Issue by chocomilku** [Fursum/mapper-influences-frontend#5]
**Is your feature request related to a problem? Please describe.**
It gets cluttered (especially on smaller breakpoints) when you are typing very slow and it gets updated immediately (it also unfocuses from the textarea) 
![image](https://github.com/Fursum/mapper-influences-frontend/assets/88021521/82bde05d-3529-4ac1-aee3-c995c6306ba7)

**Describe the solution you'd like**
Visual cues in the textarea when the text update is being sent 
for example: a loading icon when submitting and a checkmark when it gets updated
similar to this:
![image](https://github.com/Fursum/mapper-influences-frontend/assets/88021521/abe2963a-38aa-44b5-a12a-9cd83e46fa13)

**Describe alternatives you've considered**
A save button that would update the text only when clicked. also would warn (maybe with prompt()) when you tried to leave the page when there is unsaved changes.

**Additional context**

**Comment by Fursum** [comment]
i recently increased the delay to avoid the toast spam but the suggestion is valid. i will look into changing the success indicators

**Comment by Fursum** [comment]
fixed with https://github.com/Fursum/mapper-influences-frontend/commit/1486bd1ce8634e6da1fa436ec33ed6adf5c25a31
forgot to close
