### ISSUE TITLE
Map search bar should ignore Enter keypress

### ISSUE THREAD

**Issue by tilda** [Fursum/mapper-influences-frontend#8]
**Describe the bug**
When adding a map to an influence's Featured Map list, pressing enter on the search bar will close the modal without adding any map.

**To Reproduce**
1. Go to add a Featured Map on any influence in your profile
2. Select the search bar in the modal
3. Press Enter
4. Modal closes without anything happening (note: this happens even when a map is selected)

**Expected behavior**
Keypress should likely either be ignored or submit the request

**Screenshots**
*N/A*

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 126

**Additional context**
*N/A*

**Comment by Fursum** [comment]
fixed by https://github.com/Fursum/mapper-influences-frontend/commit/fc18e6361339ccb0360c985fe81b704a7824b8bc
