### ISSUE TITLE
Manual map id input box

### ISSUE THREAD

**Issue by Dopaminos** [Fursum/mapper-influences-frontend#9]
**Is your feature request related to a problem? Please describe.**
I want to set a featured map of someone, but it's DMCA-ed, so i can't do it through search

**Describe the solution you'd like**
Add manual `*insert link*` field so i could add maps with using osu site instead of using search here as alternative

**Comment by Fursum** [comment]
added https://github.com/Fursum/mapper-influences-frontend/commit/ae6fd22d9fbcf6440c4e9b684450a1b39a894c82
